server:
  port: 8082

spring:
  datasource:
    hikari:
      source:
        username: root
        password: rootpassword
        jdbc-url: jdbc:mariadb://localhost:33307/db_name
      replica:
        replica-List:
          -   name: replica1
              username: replica1
              password: rootpassword
              jdbc-url: jdbc:mariadb://localhost:43307/db_name
  jpa:
    hibernate:
#      ddl-auto: create-drop
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        open-in-view: false
    jackson:
      deserialization:
        adjust-dates-to-context-time-zone: false
      time-zone: Asia/Seoul

kafka:
  consumer:
    group-id: resume-command
  bootstrap-servers: localhost:9092
  topics:
    resume-status: resume-status
    user-status: user-status